### ISSUE TITLE
error when using multiple cores

### ISSUE THREAD

**Issue by svanhal71** [gtonkinhill/panaroo#36]
site-packages/joblib/externals/loky/process_executor.py:706: 
UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  "timeout or by a memory leak.", UserWarning

When I use -t option with 40 cores - I get this error prior to generating pan or core genome 
(and after initial results and after processing paralogs) - resulting in not generating the aligned sequences. 

Thanks

**Comment by gtonkinhill** [comment]
Hi, this could be a problem with the multiple sequence aligner. Has panaroo generated the "summary_statistics.txt" file? If so has it generated any of the MSA files?

**Comment by svanhal71** [comment]
Yes - the summary_statistics.txt has been created; A temp folder with aligned sequences exists but the aligned_gene_sequences folder is empty. 

What is the final refinement step?

Thanks

**Comment by gtonkinhill** [comment]
Hi, apologies for the delay in getting back to you.

We've recently updated some of the code so the issue may now be resolved. If it's an issue with panaroo interacting with MAFFT it might be best to try installing panaroo in a clean conda environment.

```
conda create -n pan python=3
conda activate pan
conda install -c bioconda/label/cf201901 panaroo
```

**Comment by marade** [comment]
I am also experiencing this error.  I installed via pip3 a few hours ago.

**Comment by gtonkinhill** [comment]
Hi, 

We have just pushed a new release that should check whether panaroo can see the multiple sequence aligner.  It's currently on GitHub and should be on conda soon.

If this fails it would be great if you could send me a more detailed error message and I will hopefully be able to find the source of the problem.

**Comment by marade** [comment]
Still the same error:

Number of searches to perform:  1105892                                         Searching...
16it [01:12,  4.50s/it]/usr/local/lib/python3.6/dist-packages/joblib/externals/l
oky/process_executor.py:706: UserWarning: A worker stopped while some jobs were
given to the executor. This can be caused by a too short worker timeout or by a
memory leak.
  "timeout or by a memory leak.", UserWarning
20it [01:28,  4.41s/it]

**Comment by gtonkinhill** [comment]
This is warning issued by the joblib package rather than an error. It should not alter the results. If you notice it does please let us know and if you are able to provide  a small reproducible example that would be great.
